import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import Provider from "@/src/components/Provider";
import "@ant-design/compatible";
import "antd/dist/reset.css"; 
export const metadata: Metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       >
           <Provider>
           <NextTopLoader
            color="#CFFFA3"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
           />
        {children}
       
           </Provider>
      </body>
    </html>
  );
}
